ess-dmsc/forward-epics-to-kafka

- README.md
- src/Converter.cxx
- src/Converter.h
- src/KafkaOutput.cxx
- src/KafkaOutput.h
- src/KafkaW.cxx
- src/KafkaW.h
- src/Main.cxx
- src/Main.h
- src/MainOpt.cxx
- src/MainOpt.h
- src/Stream.cxx
- src/Stream.h
- src/schema-config-global.json
Produce status messages on topic given by `status-uri` in either config file or on command line.
> Produce status messages

- cmake/FindEPICSV4.cmake
- src/CMakeLists.txt
- src/Main.cxx
- src/Main.h
- src/Stream.cxx
- src/Stream.h
- src/Streams.cxx
- src/Streams.h
- src/tests/CMakeLists.txt
- src/tests/Streams_test.cxx
- src/tests/streams_tests.cxx
I have added a separate streams class as a container for `stream`. 
As well as this, I have added some unit tests to test the functionality of the new streams class and used a mock `stream` object to put inside it.
> Add separate streams class and add tests for it

- src/EpicsClient.cxx
- src/schemas/f142/f142.cxx
> Request field explicitly for channel access

- src/MainOpt.cxx
- src/MainOpt.h
- src/tests/CMakeLists.txt
- src/tests/MainOpt_tests.cxx
some simple changes including moving some code out of the functions in `MainOpt.cxx` into their own seperate functions and variable name changes to be more descriptive
> MainOpt refactoring

- src/MainOpt.cxx
- src/MainOpt.h
- src/tests/CMakeLists.txt
- src/tests/MainOpt_tests.cxx
> MainOpt tests and refactoring

- Jenkinsfile
- conan/conanfile.txt
- conan/conanfile_win32.txt
- src/MainOpt.h
This adds the windows build to the conanised pipeline build.
It also fixes the windows build that was broken.
> Add windows build to the pipeline

- src/CURLReporter.h
- src/Main.cpp
- src/Main.h
> Factor CURLReporter into new file

- src/RangeSet.h
Remove some commented code.
Closes #63
> Remove commented code

- PULL_REQUEST_TEMPLATE.md
As a step towards improving code quality, I am introducing a PR review template.
I have taken one used in IBEX and modified it for our needs.
It is a first attempt, so we can refine it with time.
I have chosen the forwarder as it is something that is being worked on across all the facilities and has no outstanding PRs (apart from this one).
> Added first version of PR template

- src/Kafka.cpp
- src/Main.cpp
- src/Main.h
This contains some very minor changes that were noted in the code review in April.
Closes #78 
A few renames, some documentation corrections, removed some unused code and added an explicit.
N/A
N/A
---
---
> Added some minor changes

- README.md
Update `README.md` to include link to system tests documentation.
Closes #88 
---
---
> Include system tests documentation in README.md

- system-tests/test_example.py
Adds a system test to check scalar string PV values are forwarded. It tests the functionality being added in #84
Currently this test fails, is it the fault of the test or implementation in #84?
Note, we are not yet running system tests on Jenkins, they are too heavy to run on every commit so we need to figure out how to have them only run on PRs or periodically. Instructions on running them manually are here: https://github.com/ess-dmsc/forward-epics-to-kafka/blob/master/system-tests/README.md
*No associated issue*
Merge when the test passes because the test or #84 has been fixed.
---
---
> Add system test for forwarding scalar string PV update

- README.md
Adding documentation to state that the forwarder uses MDEL monitoring rather than ADEL (Archive monitoring)
Closes #83 
No change in functionality
No unit tests modified
Updated `README.md`
---
---
> Updating documentation to include monitoring deadband specification

- src/EpicsClient/EpicsClientMonitor.cpp
- src/Stream.cpp
- src/tests/streams_tests.cpp
Small changes as requested in #105 
No issue
No change in functionality
Changed `streams_tests` to use make_unique.
---
---
> Ring buffer PR changes

- Jenkinsfile
Added Ubuntu 18.04 build node to pipeline
Removed Ubuntu 16.04 and 17.10 build nodes from pipeline
Closes #134 
No change in functionality.
---
---
> Adding Ubuntu 18.04 build node, removing 16.04 and 17.10

- src/Config.h
- src/EpicsClient/EpicsClientMonitor.cpp
- src/EpicsClient/EpicsClientMonitor.h
- src/FlatbufferMessage.cpp
- src/FlatbufferMessage.h
- src/Forwarder.cpp
- src/Kafka.h
- src/KafkaOutput.h
- src/SchemaRegistry.cpp
- src/Stream.h
- src/Streams.cpp
- src/Timer.h
Some of the doxygen comments' style differed from the bulk comment style.
This corrects those.
N/A
Changed comments style matches LLVM style.
N/A
N/A
---
---
> Changed the doxygen style

- conan/conanfile_win32.txt
Updated cli11 version to 1.5.3 from 1.3.0 in conanfile.
Closes #148 
---
---
> Updating cli11 version in windows conanfile

- src/CURLReporter.h
- src/CommandHandler.cpp
- src/ConfigParser.cpp
- src/ConversionWorker.cpp
- src/Converter.cpp
- src/EpicsClient/EpicsClientFactory.cpp
- src/EpicsClient/EpicsClientMonitor.cpp
- src/EpicsClient/FwdMonitorRequester.cpp
- src/FlatbufferMessage.cpp
- src/Forwarder.cpp
- src/Kafka.cpp
- src/KafkaOutput.cpp
- src/KafkaW/Consumer.cpp
- src/Main.cpp
- src/MainOpt.cpp
- src/Stream.cpp
- src/Streams.cpp
- src/Timer.cpp
- src/logger.cpp
- src/logger.h
Replacing the `LOG(int)` calls with a severity enum just like the file writer. 
Closes #117
No change in functionality so just check log calls. 
No logic modified
---
---
> Use enum for log level severity 

- Jenkinsfile
Remove previous build docker containers in case of interference between system tests on node
Closes #170 
PR build passes
---
---
> Sort out jenkins system test interference

- CMakeLists.txt
- Dockerfile
Moved the conan step outside of cmake so it doesn't get run every time the forwarder is built unless something is outdated. 
Closes #172 
System tests still pass. Note: they may not be as fast the first run but I have tested and they run much quicker when source changes are made (and also when the code doesn't change)
---
---
> Making system tests run more quickly

- src/KafkaW/BrokerSettings.cpp
- src/logger.cpp
Only a tiny change as I did most of the work for this ticket on a seperate PR. 
Making the log levels consistent so removing any ERROR calls from debug statements and so on. 
Closes #2 
`logger.cpp`
`KafkaW/BrokerSettings.cpp`
---
---
> Logging levels consistency

- Dockerfile
- conan/conanfile.txt
dm2 is no longer in the repository it seems and the system tests are failing
---
---
> Fixing system tests

- CONTRIBUTING.md
Updated CONTRIBUTING.md
Now contains naming conventions 
Closes #190 
---
---
> re #190 introduce naming conventions

- src/KafkaW/BrokerSettings.h
Changed BrokerSettings from class to struct.
Closes #201 
*List the changes in functionality or code that the reviewer needs to review.*
---
---
> re #201 changed class to struct

- Dockerfile
Didn't need to replace ADD as the functionality is built in. However, this is required to be merged for the other system tests to pass. 
Closes #212 
---
---
> Updating conan version and registry file

- codecov.yml
Disabling the patch status that stop merges even when PRs increase coverage. 
Closes #213 
N/A
N/A
N/A
---
---
> Disable annoying codecov patches 

- src/KafkaW/Consumer.cpp
- src/KafkaW/Consumer.h
- src/KafkaW/Producer.cpp
- src/KafkaW/Producer.h
introduced both Producer and Consumer interface.
Variables' names changed to make the code more readable.
Closes #200 
Closes #207 
Producer.h/cpp
Consumer.h/cpp
---
---
> 200 kafkaW producer/consumer interface

- codecov.yml
> properly disabling annoying codecov status stuff 

- Jenkinsfile
This means logs and junit output should still be published when a system test fails. 
Closes #217 
N/A
N/A
N/A
---
---
> Move log and junit output archiving into finally step

- CONTRIBUTING.md
Adding an issues section in the CONTRIBUTING.md file.
---
---
> Add Issues section in CONTRIBUTING.md

- Jenkinsfile
Adding timer for system tests to stop hanging runs.
> Adding timeout for system tests

- documentation/usage.md
- src/CMakeLists.txt
- src/KafkaW/Consumer.cpp
- src/KafkaW/Consumer.h
- src/KafkaW/KafkaW.cpp
- src/KafkaW/Producer.cpp
- src/KafkaW/Producer.h
- src/tests/Consumer_tests.cpp
- src/tests/Producer_tests.cpp
Documentation and refactoring for the new cpp rdkafka wrapper.
None
relates to DM-1142
No changes in functionality
Some variables in tests renamed. 
have also added a very simple test for the produce() method as we may want to add some conditionals in there at some point (ie using it for status messages or plain json)
Updated readme to show the broker being mandatory for any topics used in the forwarder. 
---
---
> Documentation for the kafka cpp code

- system-tests/README.md
- system-tests/helpers/flatbuffer_helpers.py
- system-tests/helpers/kafka_helpers.py
- system-tests/test_forwarding.py
- system-tests/test_generate_fake_epics_data.py
Added GIVEN, WHEN, THEN descriptions to system tests.
Removed tests which duplicate coverage.
Added more printing on test failure to clarify what has gone wrong.
> Improve system tests

- src/KafkaW/ProducerTopic.cpp
- src/KafkaW/ProducerTopic.h
- src/RangeSet.h
- src/tests/CMakeLists.txt
- src/tests/RangeSetTests.cpp
n/a
- Fixed one memory leak in the kafka code.
- Fixed one string formatting bug and added unit test for that code.
> Minor bug fixes

- Dockerfile
- docker_launch.sh
relates to DM-1406
Deleting the conan cache and src objects in the docker image. This should reduce final image size by a lot.
> More dockerfile slimming

- system-tests/README.md
DM-1511
Have added general architecture info, developer notes and current issues.
> Add developer notes and general architecture info into systests readme 

- src/CMakeLists.txt
- src/tests/BrokerSettingsTests.cpp
- src/tests/CommandHandlerTests.cpp
- src/tests/ConfigParserTests.cpp
- src/tests/ConsumerTests.cpp
- src/tests/EpicsClientMonitorTests.cpp
- src/tests/EpicsClientRandomTests.cpp
- src/tests/JsonTests.cpp
- src/tests/ListenerTests.cpp
- src/tests/ProducerDeliveryCbTests.cpp
- src/tests/ProducerTests.cpp
- src/tests/RangeSetTests.cpp
- src/tests/StreamTestUtils.cpp
- src/tests/StreamTestUtils.h
- src/tests/StreamTests.cpp
- src/tests/StreamsTests.cpp
- src/tests/TimerTests.cpp
- src/tests/URITests.cpp
- src/tests/UnitTests.cpp
Treat library as library.
See code changes.
> Treat library as library in unit tests.

- src/tests/ProducerTests.cpp
N/A
Some tests were leaking memory, now they don't.
> Removed memory leaks in tests

- Jenkinsfile
Part of DM-972
Changed to use the jenkins-shared-library in the Jenkinsfile.
This reduces the boilerplate code a little and ensures that the latest build node images are used without having to update the Jenkinsfile.
*Reviewer:*
Please check that all the expected build artifacts and coverage reports are successfully produced before merging this pull request.
> Modernise jenkinsfile

- documentation/commands.md
- documentation/development.md
> Documentation updates.

- src/schemas/tdc_time/TdcTime.cpp
*DM-1699
Added more complete error messages. Turns out it was a bug in the config and not in the forwarder.
*Add a description of the work done. The aim is provide information to help the reviewer review the PR efficiently.
See [CONTRIBUTING.MD](CONTRIBUTING.MD) for more information on code standards etc.*
> Dm 1699 wrong pv type for tdc ts

- src/CMakeLists.txt
- src/Config.cpp
- src/ConfigParser.cpp
- src/EpicsClient/ChannelRequester.h
- src/EpicsClient/EpicsClientFactory.h
- src/EpicsClient/EpicsClientInterface.h
- src/EpicsClient/EpicsClientRandom.cpp
- src/EpicsClient/EpicsClientRandom.h
- src/EpicsClient/FwdMonitorRequester.h
- src/EpicsPVUpdate.h
- src/Forwarder.cpp
- src/Kafka.cpp
- src/KafkaW/ConsumerMessage.h
- src/KafkaW/KafkaEventCb.h
- src/KafkaW/ProducerDeliveryCb.h
- src/KafkaW/ProducerMessage.h
- src/KafkaW/ProducerStats.h
- src/KafkaW/ProducerTopic.cpp
- src/KafkaW/ProducerTopic.h
- src/tests/BrokerSettingsTests.cpp
- src/tests/ConsumerTests.cpp
- src/tests/ListenerTests.cpp
- src/tests/ProducerDeliveryCbTests.cpp
- src/tests/ProducerTests.cpp
*Specify the associated JIRA ticket, e.g. DM-1234.*
*Add a description of the work done. The aim is provide information to help the reviewer review the PR efficiently.
See [CONTRIBUTING.MD](CONTRIBUTING.MD) for more information on code standards etc.*
> Log message improvements

- conan/conanfile.txt
- conan/conanfile_win32.txt
- conan/conanfile_win32_no_epics.txt
- src/KafkaW/BrokerSettings.h
- src/tests/ConfStandIn.h
- src/tests/ConsumerTests.cpp
- src/tests/MockMessage.h
- src/tests/ProducerTests.cpp
Updated librdkafka from 0.11.4 to 1.2.0
A couple of client config settings had to be changed, I have explicitly set them to the same as the default value set by the library.
> Update librdkafka to 1.2.0

- src/Forwarder.cpp
- src/Forwarder.h
- src/MetricsTimer.cpp
- src/MetricsTimer.h
- src/logger.h
Fix winsock include problem on Windows
@DolicaAkelloEgwel this should fix the WIndows build problem on your development branch.
> Fix winsock include clash

- PULL_REQUEST_TEMPLATE.md
- changes.md
To bring Forwarder in line with https://github.com/ess-dmsc/kafka-to-nexus/pull/503
> breaking changes -> changes

- Dockerfile
- src/KafkaW/Producer.cpp
- src/KafkaW/Producer.h
- src/KafkaW/ProducerTopic.cpp
- src/KafkaW/ProducerTopic.h
Related to [DM-1808](https://jira.esss.lu.se/browse/DM-1808)
Adds a `createTopic` method to the `Producer`.
*Changes should be documented in `changes.md`*
> Avoid using topic in produce

- conan/conanfile.txt
- conan/conanfile_win32.txt
- conan/conanfile_win32_no_epics.txt
DM-1812
Update schema package, also updates flatbuffers to 1.11.0 (hopefully resolving occasional package build failure on Windows).
> Update schema conan package

- system-tests/config-files/forwarder_config_no_command.ini
- system-tests/helpers/kafka_helpers.py
- system-tests/helpers/producerwrapper.py
- system-tests/test_forwarding_configured_from_file.py
- system-tests/test_forwarding_configured_over_kafka.py
DM-1860
Attempt to make the system tests a little clearer that they cover "reconfiguration" of the forwarder.
> Make system test clearer that reconfiguration is occuring

- src/Forwarder.cpp
- src/Forwarder.h
N/A
This code does nothing. BrokerConfig.HostPort has a default value if a value is not supplied and I don't think you can pass an empty string to CLI and if you can and do, well, good luck!
*Changes should be documented in `changes.md`*
> This code does nothing!

- src/CommandHandler.cpp
- src/CommandHandler.h
- src/Config.cpp
- src/Config.h
- src/ConfigParser.cpp
- src/ConfigParser.h
- src/Forwarder.cpp
- src/MetricsReporter.cpp
- src/tests/CommandHandlerTests.cpp
- src/tests/ConfigParserTests.cpp
- src/tests/ListenerTests.cpp
N/A
Renamed ConfigCB to ConfigCallback - I don't think it will make the executable bigger ;)
Moved a method to a more suitable class.
Added an enum class for the types of command.
Fixed up the tests to match the changes and some minor tidying.
*Changes should be documented in `changes.md`*
> Refactoring of command handler
