ess-dmsc/forward-epics-to-kafka

src/CMakeLists.txt
src/Main.cxx
src/MainOpt.cxx
src/tests/remote.cxx
src/tests/uri.cxx
src/uri.cxx
src/uri.h

Some build environments still have only ancient compilers installed.
There is a need to solve this immediately.
Therefore, remove usage of regular expressions from project as a step in that direction.

Remove usage of regex

---

src/KafkaW.cxx

In Consumer::Consumer(...) code was added by `1f3a1b73` before the init() call
which resulted in the usage of the members of the incompletely initialized
class.

Fix regression introduced by 1f3a1b73

---

CMakeLists.txt
Jenkinsfile
README.md
cmake/FindGoogletest.cmake
cmake/conan.cmake
src/CMakeLists.txt

Closes #44 
With these changes:
- `gtest` is reliably picked up from Conan, even when the repository or system-installed library is present.
- `Conan` does not have to be run manually. This avoids problems with other tools/IDEs running `CMake`, and populating the cache, before `Conan` has been run.
- To build without `Conan` `-DCONAN_DISABLE=true` must be passed to `CMake`. The option is displayed in the README.

Conan improvements

---

Jenkinsfile
src/EpicsClient.cpp

This adds CppCheck as part of the Jenkins build.
The results can then be viewed in Jenkins, for example: https://jenkins.esss.dk/dm/job/ess-dmsc/job/forward-epics-to-kafka/job/jenkins_cppcheck_test/18/warnings2Result/

Added Jenkins CppCheck reporting

---

Jenkinsfile
README.md
build-script/invoke-cmake-from-jenkinsfile.sh
build-script/jenkins-build.sh
cmake/FindGoogletest.cmake

Just changing the default value of REQUIRE_GTEST in the cmake so that the tests will be build by default. If REQUIRE_GTEST is set to false it will no longer build the test target. 
Closes #101 
Check running the forward-epics-to-kafka target builds tests target by default. 
No unit tests modified. 
---
---

Making unit tests build by default

---

CMakeLists.txt
Jenkinsfile
conan/conanfile.txt

Update release artefact archiving for integration test deployment. This incorporates changes that existed in the _essiip-deployment_ branch, which was very outdated. Conan package versions have been updated and some container settings added to the Jenkinsfile (setting CPU and memory usage). The main CMakeLists.txt file has been modified to call `conan_cmake_run` without `NO_OUTPUT_DIRS` when building in release mode.
Closes DM-936.
The Jenkins build should complete, creating a .tar.gz archive with a release build of the forwarder, including all dependencies. The previously existing debug mode builds should not be changed, besides now using more recent versions of the Conan packages..
No tests have been modified.
There was an issue with the test coverage commands hanging in many of the …

JIRA DM-936 incorporate essiip-deployment

---

src/Forwarder.cpp

Truncate only for stdout, but keep full output for Kafka.

Fix truncated status output which was meant for Kafka

---

Jenkinsfile

Add a BUILD_INFO artefact with project name, commit SHA and Jenkins build number. As we deploy the archive directly from Jenkins, this makes it easier to identify which version has been deployed and can be displayed in the integration test.
N/A
A new artefact containing project name, branch, Git commit SHA and Jenkins build number is archived in Jenkins.
N/a
N/A
---
---

Add file with build information

---

Dockerfile
system-tests/conftest.py
system-tests/docker-compose-fake-epics.yml
system-tests/docker-compose-idle-updates-long-period.yml
system-tests/docker-compose-idle-updates.yml
system-tests/docker-compose.yml
system-tests/requirements.txt

So the docker image does not have to built manually before running system tests. It should check whether parts of the image are out of date and rebuild just those steps rather than building all of the other images with it. 
This also means we can run the system tests in Jenkins easily (issue #74 )
Closes #87 
System tests pass 
Image is only rebuilt once if it doesn't exist beforehand then used for the rest of the test fixtures.
---
---

Adding intelligent rebuild with docker in the system tests

---

src/EpicsClient/EpicsClientRandom.cpp
src/tests/EpicsClientRandom_tests.cpp

Populate timestamp fields in PVStructures from EpicsClientRandom so that the resultant messages in Kafka have suitable timestamps set for the File Writer to record and compare against its start time.
Closes #154
Could test against the File Writer using https://github.com/ess-dmsc/mohican-yak
Just temporarily remove the Forwarder from the docker-compose and run it manually.
New unit test in `EpicsClientRandom_tests.cpp` to check that the timestamp fields are populated.
---
---

Populate timestamp fields in PVStructures from EpicsClientRandom

---

src/SchemaRegistry.h
src/Stream.h
src/Timer.h

By accident (don't ask) I built the forwarder with a newer version of clang and it gave a few warnings relating to missing virtual destructors.
To me these warnings seem valid as the classes (or their children) identified usually end up in some kind of pointer.
N/A
The changes are sensible.
N/A
N/A
---
---

Added missing virtual destructors

---

Dockerfile
system-tests/conftest.py
system-tests/helpers/epics_helpers.py
system-tests/requirements.txt
system-tests/test_forwarding.py

Removes the dependency for EPICS to be on the system running the tests and uses a docker call instead of an EPICS library call.
Closes #141 
Run system tests and check they all pass still. 
Updated `requirements.txt` 
---
---

Replacing pyepics with docker call through IOC container

---

src/RangeSet.h
src/Stream.cpp

Replacing `Range` in `RangeSet.h` with a std::pair which has the same comparison abilities to my knowledge. 
The functions in this class didn't seem to be used.  
Closes #218 
`Stream.h` has been modified as well as `Rangeset.h` 
System tests should pass 
Unit tests should pass 
None modified. 
None. 
---
---

Replace Range with std::pair

---

src/CommandHandler.h
src/Config.cpp
src/Config.h
src/Forwarder.h

Deleted callback interface from Config.h/cpp. I believe it was once used for some mocks, now it was unused.
Similarly removed unused variable and method from Listener.
Closes #229 
Commandhandler.h
Config.h/cpp
Forwarder.h
n/a
n/a
---
---

229 delete callback interface

---

README.md

Adding the output of `--help` to the README of the forwarder. 
Although this does add another step in maintenance, the only changes that affect CLI options are usually breaking, so should be documented in the README anyway.
Closes DM-1210
None 
None
Updated README.md 
---
---

Adding --help output to README

---

system-tests/conftest.py

Adding the forwarder container output to jenkins if the program terminates. Previously this was uncaught as it would stop logging to a file (done through the command line args) 
Closes DM-1244
To test: 
Comment out `log-file` in one of the system test INI files and check the container outputs all logs to stdout 
None
None
---
---

re DM-1244 Adding forwarder container output to jenkins

---

Dockerfile
Jenkinsfile
system-tests/conftest.py

Make dockerised system tests use cached binary Conan packages instead of building them from source.
Closes #DM-1267.
The system tests should download binary Conan packages from the local server, instead of building them from source.
n/a
Changed system tests.
---
---

Add local conan server in system tests Dockerfile

---

Jenkinsfile

Removing the slacksend call so failures are not sent to the slack channel.
---
---

Removing slack channel bot call in jenkinsfile

---

src/KafkaW/Consumer.cpp

The Forwarder was previously assigning to the highest offset on a partition, therefore meaning that if there were already commands on the topic it was assigned to for receiving command messages, it would try and add PVs that might not exist anymore. 
DM-1322
Changed set_offset call to assign from highest offset on each `RdKafka::TopicPartition.`
None modified. 
None
---
---

Changing Consumer to assign to highest offset on partition rather than lowest. 

---

system-tests/conftest.py

None
Previously every new fixture would attempt to rebuild the image (because the build step was also in the run step)
this should mean it only gets built once, so should speed the tests up and make them more robust.
It will also fail immediately now if docker fails to build

Stopping system tests from rebuilding the image every fixture

---

src/CMakeLists.txt

Changes to CMake so that curl not being found does cause CMake to fail.
I was previously having to explicitly point CMake at CURL on my system.

Fix not requiring CURL

---

Jenkinsfile

None
Updating the centos build node image, removing scl enable from the system test calls to make more readable, also using python 3.6 now

Update centos build nodes to 4.0.0 and remove scl enable python

---

system-tests/helpers/flatbuffer_helpers.py

DM-1387
Add a check to make sure the timestamp exists (not epoch time) in the flatbuffer message that is forwarded.

Adding a timestamp check in the flatbuffer helpers in the sys tests

---

src/FlatbufferMessage.h
src/KafkaOutput.cpp
src/KafkaW/ProducerMessage.h
src/KafkaW/ProducerTopic.cpp
src/schemas/f142/f142.cpp
src/tests/CMakeLists.txt
src/tests/tests.cpp
system-tests/compose/docker-compose-kafka.yml
system-tests/helpers/kafka_helpers.py
system-tests/test_forwarding.py

DM-1283
Uses the PV name as the message key for PV update messages published to Kafka. This will ensure the order of published PV messages is maintained.
Added a system test to cover this behaviour: `test_forwarding.py`, `test_updates_from_the_same_pv_reach_the_same_partition`

Use PV name as message key

---

.dockerignore
Dockerfile

relates to DM-1406
I have bundled steps into layers as more layers in the docker image means more space when building. This approach shouldn't take any longer than usual. The image will rebuild when the conanfile updates, however as this only happens every so often and it already causes the build time to increase I don't think this is an issue. 
When merged: create and push new image to docker hub

Slimming down docker image

---

Jenkinsfile
src/EpicsClient/FwdMonitorRequester.cpp
src/Forwarder.cpp
src/Forwarder.h
src/Kafka.h
src/KafkaOutput.cpp
src/KafkaOutput.h
src/KafkaW/Consumer.cpp
src/KafkaW/Consumer.h
src/KafkaW/Producer.cpp
src/KafkaW/ProducerStats.h
src/Stream.cpp
src/URI.h
src/tests/BrokerSettings_tests.cpp
src/tests/CommandHandler_tests.cpp
src/tests/Consumer_tests.cpp
src/tests/ProducerDeliveryCb_tests.cpp
src/tests/Producer_tests.cpp

N/A
@SkyToGround did a great job fixing cppcheck warnings: let's not let that go to waste.
I have added a check to Jenkins that will make the build unstable if the number of warnings exceeds n, where n is the current number of warnings (n = 2).
One of the current warnings is nonsense and unavoidable (missingInclude) the other might be legit (something to do with the GELF stuff).
I have fixed a small number of warnings and suppressed some others too.

Set build unstable if cppcheck warnings increase

---

src/KafkaW/Producer.cpp
src/tests/Producer_tests.cpp

DM-1480
Prior to these changes RdKafka::Producer.poll() may not be called sufficiently frequently when producing at a high rate. This results in successful publish events not getting handled, therefore RdKafka does not clear the messages from the producer queue, it eventually fills up completely and at that point message publishing fails.
I've added a test to `Producer_tests.cpp` which checks that `poll` is called each time we call produce. I've added a non-blocking call to `poll` in produce. Note, there is no significant performance hit from this, it only polls the local producer, it does not do anything across the network.
@mattclarke The changes are identical to those made in the File Writer except that the unit test uses gmock rather than trompeloeil.

Add sufficient producer poll calls

---

src/ConfigParser.h
src/MainOpt.cpp
src/URI.cpp
src/URI.h
src/tests/URI_tests.cpp

* DM-1444
* Made the forward slashes ("//") in URIs optional.
* Added some unit tests.
* Improved the exception error message when failing to parse host name.
* Made the CLI11 library write out an error message on (some) poorly formatted address strings.
* Removed references to the forward slashes from the help text.
* Improved a function name.

Improve/fix URI code and related error messages

---

src/EpicsClient/EpicsClientInterface.h
src/EpicsClient/EpicsClientMonitor.cpp
src/EpicsClient/EpicsClientMonitor.h
src/EpicsClient/EpicsClientRandom.cpp
src/EpicsClient/EpicsClientRandom.h
src/EpicsClient/FwdMonitorRequester.cpp
src/tests/StreamTestUtils.h

DM-1505
Added mutex protection to the cached PV update used for the periodic update feature.

Protect the cached update with a mutex

---

system-tests/helpers/kafka_helpers.py
system-tests/test_forwarding.py
system-tests/test_forwarding_no_command_at_startup.py
system-tests/test_generate_fake_epics_data.py
system-tests/test_idle_pv_updates.py
system-tests/test_idle_pv_updates_long_period.py
system-tests/test_longrunning.py

A system test which tried to check updates from the same PV end up in the same partition was unreliable.
Replaced the problem test with a simple check that the message key is set to the PV name. In other words, test that our code does what we intend rather than that Kafka itself behaves as we expect.

Replace unreliable system test

---

Dockerfile
conan/conanfile.txt
conan/conanfile_win32.txt

None
Switched to the remotes.json which is required for the most recent version of conan in the dockerfile for the system tests
- make sure the system tests pass

conan registry.json switch to remotes.json

---

README.md

None
Replaced the outdated list of remotes to a link to the conan-configuration repository which contains the instructions.

Replace outdated conan remotes with instructions on conan-configuration

---

src/tests/CMakeLists.txt

N/A
The tests were building without the -Werror flag.

Tests were missing -Werror flag

---

Jenkinsfile

These flags are required for the application to find its dependencies as
provided in the archived artefact, without setting LD_LIBRARY_PATH.
n/a
See text above.

Add CMake options to release build

---

CMakeLists.txt
cmake/Versioning.cmake
cmake/templates/Version.h.in
src/CMakeLists.txt
src/Main.cpp
src/MainOpt.cpp
src/MainOpt.h

DM-1088
Add versioning support with CMake, as done for kafka-to-nexus and event-formation-unit. In this case, the `GetVersion` function had to be put in a separate namespace, as the name conflicted with what seemed to be a Windows function.

DM-1088: Add CMake versioning support

---

src/EpicsClient/EpicsClientRandom.cpp
src/EpicsClient/FwdMonitorRequester.cpp
src/EpicsPVUpdate.h

No ticket, just cleaning up something I noticed when working on another issue.
Removed `ts_epics_monitor` from `EpicsPVUpdate` as it was assigned but never accessed.
Also removed the unhelpful comment `/// Do not rely on channel, will likely go away...`
as the only person who may have some idea how it can "go away" doesn't work on this code base any more.

Remove unused field from PV Update class

---

README.md

None
The forwarder does not send commands to the filewriter, fixed a typo meaning to say "sending commands to the forwarder"

typo - changed file-writer to forwarder

---

conan/conanfile.txt
conan/conanfile_win32.txt
conan/conanfile_win32_no_epics.txt
src/MetricsReporter.cpp
src/MetricsReporter.h
src/StatusReporter.cpp
src/StatusReporter.h
src/tests/CMakeLists.txt
src/tests/MetricsReporterTests.cpp
src/tests/ReporterHelpers.cpp
src/tests/ReporterHelpers.h
src/tests/StatusReporterTests.cpp

Proposed solution to possibility of tests in #313 failing.
Added a counter for report iterations. Unit tests poll this until the expected number of iterations, or a generous maximum timeout of 10 seconds, is reached.

Count report iterations occurring so can be polled in tests

---

src/Streams.cpp

Mistakenly modified in PR #317, this just reverts the value.
Will investigate if it can be removed altogether: DM-1847

Revert "EPICS cool down" to original value

---

CMakeLists.txt

gold linker is a faster alternative to the default GNU linker on Linux.
These few lines of CMake allow us to make use of it when it is available on the system. It is already available on all of our Linux build containers.
Tested on the file writer code base:
On the machine I tested on (16 core, 4.5GHz, Ubuntu 19.10, gcc 9.2.1, ninja) it results in clean build time going from 1m7s to 58s (3 repetitions with each, all repetitions were within 300ms of each other). A reduction of ~15%. Reduction is a larger percentage for incremental builds, since linking is a larger proportion of the build time in that case.

Use gold linker when available

---

src/EpicsClient/EpicsClientMonitor.cpp
src/schemas/f142/DataFromPVStruct.cpp
src/tests/CMakeLists.txt
src/tests/GetAlarmDetailsTests.cpp

*DM-1855
I could see no unit tests for explicitly testing this part of the code base so I did not care to write my own either.

Fix crash by returning default values if no alarm field present.
